name: ZiZoRegistryApplication
version: 0.0.1
description: An absolute bare-bones web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  ServerFunctions:
    path: C:\Users\matthew.whitmore\Documents\GitHub\DartApplicationLibraries\ServerFunctions
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: ^0.1.0
transformers:
- dart_to_js_script_rewriter
